swagger: "2.0"
info:
  description: API for URL Shortener
  version: 1.0.0
  title: URL Shortener API
  contact:
    email: support@example.com
host: localhost:5000
basePath: /api
schemes:
  - http
paths:
  /shorten:
    post:
      tags:
        - URL
      summary: Create a shortened URL
      description: Takes a long URL and returns a shortened version
      operationId: createShortUrl
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: url
          description: URL to be shortened
          required: true
          schema:
            type: object
            required:
              - longUrl
            properties:
              longUrl:
                type: string
                example: "https://www.example.com"
      responses:
        200:
          description: Successfully created shortened URL
          schema:
            type: object
            properties:
              shortUrl:
                type: string
                example: "http://short.url/abc123"
        400:
          description: Invalid URL supplied
        500:
          description: Internal server error
